### ISSUE TITLE
sql file encoding

### ISSUE THREAD

**Issue by nirmalavidya** [baraskar/Worlds-Country-State-and-City-Mysql-Database#1]
Hi, what is proper encoding of the sql file?
UTF-8 show strange chars
for example
(43, 'CÃ´te dâ€™Ivoire', 0, 0, 0),

thank you

**Comment by astronomersiva** [comment]
Your file have been stored in the latin1 encoding.

This [Stack Overflow](http://stackoverflow.com/a/4779380) answer provides a pretty good explanation.

**Comment by alpacin0** [comment]
Hi, I had the same problem and took me 2 days to solve how to fix the garbled symbols even the .sql file appears to be in UTF8. Since I was on Mac, I went to my windows pc and download Notepad++, I then messed a bit with the encoding tab by changing back and forth encoding, somehow it made it to show characters correctly. To anyone running this same issue I uploaded the .sql file with the fixed encoding: Link http://s000.tinyupload.com/?file_id=36817368934906269364

**Comment by alpacin0** [comment]
Link to .sql fixed http://s000.tinyupload.com/?file_id=36817368934906269364

**Comment by xiaotangyuan** [comment]
@alpacin0 the file was deleted from server, could you upload the file again?

**Comment by alpacin0** [comment]
@xiaotangyuan Hello friend, this is easy to fix, just download Notepad++, open the sql file, convert to ANSI, Save and overwrite, then close and open the file again, Convert to UTF-8 and save again. And voila, you will have the corrected way of symbols, Anyway I did this work for you to save you time, here's the file again: https://gist.github.com/alpacin0/5aa2379a5c0ee9ac9a015ca6c83c10da Cheers!

**Comment by xiaotangyuan** [comment]
@alpacin0 thank you very much,   i found another problem in the file ,  at the line 284. line 293, line 547, line 695 and so on,  the ' â€ ' was parsed to ' _ ' ,  is this a mistake?  and how can i fix it?

**Comment by baraskar** [comment]
Sorry for very late reply.. but i already mentioned that if required, you need to do some minor changes in to this list
